Add project setup
diarisdiakite/js-group-capstone pull request #22
Opened 2023-07-31 20:42 UTC by diarisdiakite

In This PR, we should:
✅ Set up Gitflow
✅ Set up webpack
✅ Set up a JavaScript testing library (Jest)

2023-07-31 22:33 UTC, diarisdiakite commented
Kindly find the Footer added @As1imwe-Mark. 
I'll be working now on the homePage template.

2023-08-01 00:44 UTC, diarisdiakite commented
For this milestone, I:
✅ Created the main part of the homepage that keeps the layout from the wireframe:

@As1imwe-Mark, kindly find the items with the buttons to append the popup.

2023-08-01 14:09 UTC, As1imwe-Mark commented on README.md
I kindly suggest that you update the Readme file to depict the current project.

2023-08-01 14:12 UTC, As1imwe-Mark commented on src/modules/globalElements/api.js
> +    const errorMessage = `Couldn't create the score, ${error}`;
Hello, kindly update the error message to align with the project topic.

2023-08-01 14:15 UTC, As1imwe-Mark commented on src/assets/css/style.css
> +  position: fixed;
Kindly remove the positioning on the footer because in its fixed position it blocks some useful information on the web page.

2023-08-01 14:16 UTC, As1imwe-Mark requested changes
Overall, you've done a great job implementing the project requirements. However there are some issues you need to rectify to have a perfect project.

2023-08-02 03:11 UTC, diarisdiakite commented
In this milestone, I implemented the 
✅ Display number of likes for each item on the Homepage - Student A #12](https://github.com/diarisdiakite/js-group-capstone/issues/12)

Kindly review the code @As1imwe-Mark and I suggest that we have a validation in the morning program time to merge this in the dev branch and create a new branch before you push the popup to avoid dealing with many conflicts.

2023-08-02 18:51 UTC, As1imwe-Mark approved these changes

2023-08-03 04:05 UTC, merged